### PR TITLE
[feat #9] bot can recommend command like git.

### PR DESCRIPTION
**Pull request by Koooooo-7**
Feat #9 
Using  algo `Edit Distance`  to  match similar command.

### CODE REVIEW

**Comment by Sivyer9303** [comment]
```
private static final Multimap<Integer, String> matchResult = Multimaps.synchronizedListMultimap(ArrayListMultimap.create());
```

Why use this style to store result ?  Weather it will be thread safe ？

I suggest to use it as local variable. can u understand what i mean ? haha

**Comment by Sivyer9303** [comment]
sry too late @Koooooo-7

**Comment by Koooooo-7** [comment]
@Sivyer9303   
I used it to store the score( min edit distance) and the commands( 1 to N).
i.e, if the input string is `help` and assuming that we dont hv the command  yet but we have those commands ( hele, hlp, helper,  helpers), the results should like this.
```
score  commands
1        hele, hlp
2        helper
3        helpers
```
and then, if the score is less than the  `DEFAULT_THRESHOLD = 2`， it means that there has some similar commands to recommend for user.

---
yup, it is thread safe, see the doc of `ArrayListMultimap<K, V>` :
```
 * <p>This class is not threadsafe when any concurrent operations update the multimap. Concurrent
 * read operations will work correctly. To allow concurrent update operations, wrap your multimap
 * with a call to {@link Multimaps#synchronizedListMultimap}.
```

**Comment by Koooooo-7** [comment]
@Sivyer9303  and I fixed the thread safe bug also.
see the PR  https://github.com/Koooooo-7/K-Bot/commit/ea8b2d34ba9dc2d378b8c7e06f299dd268154249

**Pull request merged**
